sudo: required
language: node_js
node_js:
  - "9"

# install dependencies on Travis host
install:
  - npm install

# runs tests on Travis host
script:
  - npm run test-ci

before_deploy:
  - cat heroku.${TRAVIS_BRANCH}.yml > heroku.yml

deploy:
  # STAGING ENVIRONMENT: tags the generated image, push to Heroku registry and the release on the app
  - provider: heroku
    app: "$HEROKU_APP_NAME_STAGING"
    api_key:
      secure: "$HEROKU_KEY"
    skip_cleanup: true
    on:
      branch: staging

  # PRODUCTION ENVIRONMENT: tags the generated image, push to Heroku registry and the release on the app
  - provider: heroku
    app: "$HEROKU_APP_NAME"
    api_key:
      secure: "$HEROKU_KEY"
    skip_cleanup: true
    on:
      branch: master
