sudo: required
language: node_js
node_js:
  - "9"

services:
  - docker

# install Heroku toolbelt and login
before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$HEROKU_KEY" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

# install dependencies on Travis host
install:
  - npm install

# runs tests on Travis host and, if they pass, generate the image
script:
  - npm run test-ci

# STAGING ENVIRONMENT: tags the generated image, push to Heroku registry and the release on the app
deploy:
  provider: heroku
  app: "$HEROKU_APP_NAME_STAGING"
  api_key:
    secure: "$HEROKU_KEY"
  script:
    docker push registry.heroku.com/$HEROKU_APP_NAME_STAGING/web;
    heroku container:release web --app $HEROKU_APP_NAME_STAGING
  on:
    branch: staging

# PRODUCTION ENVIRONMENT: tags the generated image, push to Heroku registry and the release on the app
deploy:
  provider: heroku
  app: "$HEROKU_APP_NAME"
  api_key:
    secure: "$HEROKU_KEY"
  script:
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME
  on:
    branch: master
