version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app            # bind container's src folder to local files in order to enable webpack hot reload feature
      - /usr/src/app/node_modules # disables bind just for the container's 'node_modules' folder since they're specific to the container's specs (i.e. linux, etc)
